package com.anvsystemOOPDemo1;

public class Assignment {

	/**
	 * CREATE A CLASS APPLICATION
	 * CREATE ANOTHER CLASS MOBILEAPP
	 * ESTABLISH IS-A RELATIONSHIP(INHERITANCE)
	 * BETWEEN BOTH CLASSES
	 * 
	 * DEFINE METHODS FOR APPLICATION
	 * FOR LOGIN / LOGOUT
	 * DEFINE METHODS FOR MOBILEAPP
	 * POSTPHOTO, POSTCOMMENT ETC.
	 * REUSE LOGIN/LOGOUT FROM APPLICATION CLASS
	 */
}
