package com.anvsystem.collections;

public class Assignment {

	/**
	 * DECLARE A CLASS CALLED AS CLASSVIEW
	 * DECLARE A METHOD CALLED AS FINDAVERAGEMARKS()
	 * METHOD SHOULD ASK USER ABOUT MARKS FOR EACH STUDENT
	 * SHOULD RETURN AVERAGE MARKS OF CLASS
	 */
}
